site_name: Aviation
theme:
  name: material
  palette:
    primary: teal
  logo: assets/aia_logo.jpg

nav:
  - Home: "index.md"
  - Aviation Model: "aviation.md"

markdown_extensions:
  - footnotes
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocstrings
  - search
  - bibtex:
      bib_file: "https://api.zotero.org/groups/5782724/collections/G847TDER/items?format=bibtex"
  - mkdocs-prebuild:
      base_path: ["."]
