name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync
        env:
          UV_INDEX_GITLAB_USERNAME: ${{ vars.UV_INDEX_GITLAB_USERNAME }}
          UV_INDEX_GITLAB_PASSWORD: ${{ secrets.UV_INDEX_GITLAB_PASSWORD  }}
      - name: Lint with ruff
        run: uv run ruff check
      - name: Format with ruff
        run: uv run ruff format
      - name: Static type check with mypy
        run: uv run mypy .
      - name: Test with pytest
        run: uv run pytest
      - name: Check with pre-commit
        run: uv run pre-commit run --all-files
